# Site settings
title: Corp
description:
email:
baseurl: /ddwebdev/
twitter_username:
github_username:



# Build settings
markdown: kramdown
permalink: pretty

port: 8000

sass:
  sass_dir: assets/css
  style: :nested
