# Site settings
title: Corp
description:
email:
baseurl: /corp
twitter_username:
github_username:



# Build settings
markdown: kramdown
permalink: pretty

port: 9000

sass:
  sass_dir: assets/css
  style: :nested
